name: CI (.NET)
on: [push, pull_request]
jobs:
  build-test:
    runs-on: ubuntu-latest
    defaults: { run: { working-directory: FSI.AccessAuthentication.BackEnd } }
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v4
        with: { dotnet-version: '8.0.x' }
      - run: dotnet restore
      - run: dotnet build -c Release --no-restore
      - run: dotnet test -c Release --no-build --verbosity normal
